### ISSUE TITLE
General Feedback

### ISSUE THREAD

**Issue by Jap2-0** [CactiChameleon9/Gecko-Browser#1]
(I can split stuff off into different issues if you want, but this is mostly a lot of general stuff.)

Sorry for taking a bit on posting this, but I've been using your browser for the past couple days and it's been working very well.  Performance is great (better than the old Firefox for Android/Firefox 68), and I have yet to have it crash.  Opening/closing it, putting it in the background, and opening from other apps all work fine.  

I'm not a UI expert, but it seems fine to me, apart from one issue in the settings with narrow screens (I believe mine is 360px) where the text overlaps the buttons:
![Screenshot_2020-08-22-20-27-47](https://user-images.githubusercontent.com/40511669/90968141-11fa8400-e4b7-11ea-9387-ee7b9366ebec.png)

The best solution here would probably be to make the buttons go on top of the text, and maybe make the text a tad smaller, depending on the screen size; I guess you could also make the line wrap or the text scroll.

If it isn't too much of a hassle, making the loading bar just a pixel or two taller would be nice; it took me a little bit to realize that it existed.

Also, I think the "hide white loading page" option might be inverted - I see the white loading page with it on.

Everything else is just things that aren't implemented yet, so I think that's just about everything I've come across for now.

**Comment by CactiChameleon9** [comment]
Wow... thanks a lot! I am still amazed that someone actually used my browser for a couple of days. Thanks for the feedback!

I'll have a go at fixing the settings layout - I did do it quite badly.
I can easily increase the loading bar size, I'll do that.
I'll do some testing with the white loading page, thanks for reporting that!

**Comment by CactiChameleon9** [comment]
Most of those changes should come in the next release. In theory I have most of the code for basic tabbing now (just saving and loading URLs. I'll have a look using multiple geckosessions, so switching without reloading works, later on).

**Comment by CactiChameleon9** [comment]
OK, I have actually done some more coding now (Sorry, I have been busy). The hide white loading screen is not inverted... its just it only works with dark mode (the android setting). I probably can fix this. I should have a new release out soon

**Comment by Jap2-0** [comment]
Exciting!  I've been using it for probably 80-90% of my browsing and it's been working out pretty well.  There are a couple things that I want to test out some more because I'm not sure if they're browser issues or site issues, but I'm excited to see how it comes along and I'll see what I can get you feedback-wise in a few days.

Don't feel bad about however long it takes, I've had plenty of times where I've been really busy before too, and you don't really have any obligation to this.

**Comment by CactiChameleon9** [comment]
OK, a new release is out. I'll close this issue, and you can open another one for further improvements (if you have the time). Thank you so much for the support so far

**Comment by Jap2-0** [comment]
Excellent!  What would be the best format - one issue per suggestion, one per update, just a big checklist?

**Comment by CactiChameleon9** [comment]
I don't really mind that much, a big list will be easier for you probably, so do that if you want.
